### ISSUE TITLE
MapDB 3.0.10 with guava build fails

### ISSUE THREAD

**Issue by bratwurzt** [jankotek/mapdb#1026]
Guava dependency version is set as open-ended:
`<guava.version>[15.0,)</guava.version>`

Because of that, build with mapdb fails (in my build, where redhat repos are visible):
`Failed to collect dependencies at org.mapdb:mapdb:jar:3.0.10 -> com.google.guava:guava:jar:31.1.0.redhat-00001`

My question - why don't you set a concrete version? 

Every enterprise build I've ever encountered has these versions locked for stability and reliability reasons.

I understand I can lock these versions myself - I'm just wondering about the reason.

**Comment by jankotek** [comment]
>  I'm just wondering about the reason.

MapDB 3 was released long time ago, when JDK8 compatibility was not an issue. Exact version leave build open to security vulnerabilities. I guess pinning versus open depends on particular software school. I only put upper bound on   EC version, because I participated in development, and it was constantly downloading snapshots from private repos.

MapDB 4 (I am working on that yet again) will have no dependencies (except JDK8). It is written in Java, so  there is not even dep on kotlin-stdlib.

**Comment by jankotek** [comment]
You wrote it is failing with some custom redhat repos. I build 3.0.10 release with JDK8 only, it passed all tests. So if there is some failure that is serious, please open another bug report with stack traces and more info.

**Comment by bratwurzt** [comment]
> > I'm just wondering about the reason.
> 
> MapDB 3 was released long time ago, when JDK8 compatibility was not an issue. Exact version leave build open to security vulnerabilities. I guess pinning versus open depends on particular software school. I only put upper bound on EC version, because I participated in development, and it was constantly downloading snapshots from private repos.
> 
> MapDB 4 (I am working on that yet again) will have no dependencies (except JDK8). It is written in Java, so there is not even dep on kotlin-stdlib.

thank you for replying.

**Comment by Buwaka** [comment]
trying to get MapDB to run, even with the old 15.0 guava build, but it's not exactly playing along.
`11:00:07 PM: [ERROR] Error occurred while trying to start script:
	java.lang.NoSuchMethodError: 'com.google.common.cache.CacheBuilder com.google.common.cache.CacheBuilder.weakValues()'
	at org.mapdb.DB.<init>(DB.kt:157)
	at org.mapdb.DB.<init>(DB.kt:32)
	at org.mapdb.DBMaker$Maker.make(DBMaker.kt:490)
	at Utilities.OSRSUtilities.<clinit>(OSRSUtilities.java:94)
...
`
I realize you're already working on a 4.0, but any chance you know how to get the 3.0 to play nicely with project including gson and the likes?
