### ISSUE TITLE
Guava dependancy conflict

### ISSUE THREAD

**Issue by Buwaka** [jankotek/mapdb#1050]
trying to get MapDB to run, even with the old 15.0 guava build, but it's not exactly playing along.
`11:00:07 PM: [ERROR] Error occurred while trying to start script:
	java.lang.NoSuchMethodError: 'com.google.common.cache.CacheBuilder com.google.common.cache.CacheBuilder.weakValues()'
	at org.mapdb.DB.<init>(DB.kt:157)
	at org.mapdb.DB.<init>(DB.kt:32)
	at org.mapdb.DBMaker$Maker.make(DBMaker.kt:490)
	at Utilities.OSRSUtilities.<clinit>(OSRSUtilities.java:94)
...
`
I realize you're already working on a 4.0, but any chance you know how to get the 3.0 to play nicely with project including gson and the likes?

_Originally posted by @Buwaka in https://github.com/jankotek/mapdb/issues/1026#issuecomment-2296800955_
