### ISSUE TITLE
BTreeMap does not implement SortedMap

### ISSUE THREAD

**Issue by jtnord** [jankotek/mapdb#924]
Noticed when migrating from the ancinet 1.0.9 to 3.0.7 that the Map returned from `treeMap()` (`BTreeMap`) does not implement `SortedMap` despite the fact it is sorted according to its javadoc.

**Comment by jankotek** [comment]
It does, it implements `ConcurrentNavigableMap` interface, it extends `SortedMap`
